[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "secretcookie"
client_id = "982573539049-nf5ivbqg147d8m2s1sq3lc7g0anfeo63.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"